# Wellcome Survey Science 2020

https://wellcome.org/reports/wellcome-global-monitor-covid-19/2020

- page 45 du rapport : nombre de cas au début de l'enquête
- notion de global region

In [69]:
import pandas as pd
import pyreadstat
import pyshs

def question(v,meta):
    return meta.column_names_to_labels[v]
def modalites(v,meta):
    return meta.value_labels[meta.variable_to_label[v]]

# Chargement des données
data,meta = pyreadstat.read_sav("./wgm-full-wave2-public-file.sav")

# Recodage des variables

data["poids"] = data["WGT"]

data["pays"] = data["COUNTRYNEW"]
data["age"] = data["Age"]
data["genre"] = data["Gender"].replace({1.0: '1-Male', 2.0: '2-Female'})
data["education"] = data["Education"].replace({1.0: '1-Male', 2.0: '2-Female'})
data["revenus"] = data["Household_Income"].replace({1.0: 'Q1', 2.0: 'Q2',3:"Q3",4:"Q4",5:"Q5"})
data["region"] = data["Global11Regions"].replace(modalites("Global11Regions",meta))
data["revenus_avis"] = data["Subjective_Income"].replace(modalites("Subjective_Income",meta))

reco = {1:"1-Beaucoup", 2:"2-Un peu", 3:"3-Peu ou pas du tout",4:"3-Peu ou pas du tout",99:"4-NA"}
data["connaissance_science"] = data['W1'].replace(reco)
data["comprendre_science"] = data['W2'].replace(reco)
data["education_science"] = data["W3"].replace(modalites('W3',meta))
data["confiance_hopital"] = data["W4"].replace(reco)
data["confiance_science"] = data["W6"].replace(reco)
data["confiance_gouvernement"] = data["W5B"].replace(reco)
data["confiance_scientifiques"] = data["W5C"].replace(reco)
data["confiance_journalistes"] = data["W5D"].replace(reco)
data["confiance_medecins"] = data["W5E"].replace(reco)
data["confiance_rebouteux"] = data["W5G"].replace(reco)
# construire un indicateur en additionnant de A à G...

data["gouvernants_valorisent_scientifiques"] = data["W7C"].replace(reco)

data["socialmedia_month"] = data["W27"].replace(modalites("W27",meta))
reco = {1.0: '1-Almost every hour',2.0: '1-Almost every hour',3.0: '2-At least once a day',
 4.0: '2-At least once a day', 5.0: '3-A few days a week', 6.0: '4-Less frequently', 99.0: '5-DK/Refused'}
data["socialmedia_freq"] = data["W28"].replace(reco)
reco = {1:"1-Très souvent ou tout le temps",2:"1-Très souvent ou tout le temps",3:"2-Parfois",4:"3-Jamais",99:"NA"}
data["socialmedia_healthinfo"] = data["W29"].replace(reco)

data["science_religion"] = data["W30"].replace(modalites("W30",meta))
data["covid_impact"] = data["WP21757"].replace(modalites("WP21757",meta))
data["vaccin"] = data["WP21768"].replace(modalites("WP21768",meta))


#'wbi': 'Country income level -- World Bank most recent definition'

# 'MH3A': 'How Much Science Helps to Treat Cancer',
# 'MH3B': 'How Much Science Helps to Treat Anxiety or Depression',
# 'MH3C': 'How Much Science Helps to Treat Infectious Diseases',
# 'MH3D': 'How Much Science Helps to Treat Obesity',
#'W8': 'Work of Scientists Benefits People in (Country)',
# 'W9': 'Work of Scientists Benefits People Like You in (Country)',

In [67]:
modalites("W28",meta)

{1.0: 'Several times an hour',
 2.0: 'Almost every hour',
 3.0: 'Several times a day',
 4.0: 'Once a day',
 5.0: 'A few days a week',
 6.0: 'Less frequently',
 99.0: 'DK/Refused'}


Globally, people were more likely to express a
high degree of trust in science and scientists
in 2020 than they were in 2018: there was a
10-percentage-point increase in people saying
they trust science in general ‘a lot’, while the
percentage who said they trust scientists in
their country ‘a lot’ rose nine percentage points.


One of the largest
of these is the effect of science education,
and another is how much people think they
know about science.


Perhaps it is no surprise, then, that in 2020 trust
in scientists rose, possibly as a result of Covid-19
moving the public closer than ever to the work of
scientists fighting against the pandemic.

In [11]:
data[data["COUNTRYNEW"]=="France"]["WGT"].sum()

999.999999996304

In [12]:
data[data["COUNTRYNEW"]=="France"]["PROJWT"].sum()

54950386.999999925

In [8]:
meta.column_names_to_labels

{'COUNTRYNEW': 'Country Name',
 'WPID_RANDOM': 'Random Unique Case ID',
 'WGT': 'National weight, for analysis at the country level',
 'PROJWT': 'Population weight (included factor to project to 15+ population in each country) for analysis of pooled multi-country data',
 'FIELD_DATE': 'Study Completion Date',
 'YEAR_WAVE': 'Wave Year',
 'W1': 'How Much You Know About Science',
 'W2': 'How Much You Understand the Meaning of Science and Scientists',
 'W3': 'Highest Level of Education Where Last Learned About Science',
 'W4': 'Confidence in Hospitals and Health Clinics in (Country)',
 'W5A': 'Trust People in Neighborhood',
 'W5B': 'Trust the National Government in This Country',
 'W5C': 'Trust Scientists in This Country',
 'W5D': 'Trust Journalists in This Country',
 'W5E': 'Trust Doctors and Nurses in This Country',
 'W5F': 'Trust People Who Work at Charitable Organizations or NGOs in This Country',
 'W5G': 'Trust Traditional Healers in This Country',
 'W6': 'Trust Science',
 'W7A': 'Trust Scientists to Find Accurate Information About the World',
 'W7B': 'Trust Scientists to Do Work With Intention of Benefiting Public',
 'W7C': 'Leaders in National Govt Value Opinions/Expertise of Scientists',
 'W8': 'Work of Scientists Benefits People in (Country)',
 'W9': 'Work of Scientists Benefits People Like You in (Country)',
 'W10': 'Science and Technology Will Increase or Decrease Number of Jobs in the Area in Next Five Years',
 'W11A': 'Impact of Developments in Science on Personal Health',
 'W11B': 'Impact of Developments in Science on Quality of Environment',
 'MH2A': 'How Much Science Can Explain How the Human Body Works',
 'MH2B': 'How Much Science Can Explain How Feelings and Emotions Work',
 'W13': 'Heard of Climate Change/Global Warming',
 'W14': 'Understand the Issue of Climate Change/Global Warming',
 'W15': 'Threat of Climate Change/Global Warming to People in (Country)',
 'W15_1A': 'Base Coronavirus Decisions on Scientific Advice: National Govt',
 'W15_1B': 'Base Coronavirus Decisions on Scientific Advice: Friends/Family',
 'W15_1C': 'Base Coronavirus Decisions on Scientific Advice: The W.H.O.',
 'W15_1D': 'Base Coronavirus Decisions on Scientific Advice: Doctors/Nurses',
 'W15_1E': 'Base Coronavirus Decisions on Scientific Advice: Religious Leaders',
 'W15_2A': 'Govt Should Help Prevent/Cure Diseases Wherever They Occur',
 'W15_2B': 'Govt Should Prevent/Cure Diseases Only if Risk to This Country',
 'MH1': 'Importance of Mental Health For Well-Being',
 'MH3A': 'How Much Science Helps to Treat Cancer',
 'MH3B': 'How Much Science Helps to Treat Anxiety or Depression',
 'MH3C': 'How Much Science Helps to Treat Infectious Diseases',
 'MH3D': 'How Much Science Helps to Treat Obesity',
 'MH4A': 'Important for National Govt to Fund Research on Cancer',
 'MH4B': 'Important for National Govt to Fund Research on Anxiety/Depression',
 'MH5': 'Someone Local Comfortable Speaking About Anxiety/Depression',
 'MH6': 'Friends/Family Have Been Anxious/Depressed',
 'MH7A': 'Have Been Anxious/Depressed',
 'MH7B': 'Age When First Felt Anxious/Depressed',
 'MH7B_2': 'Age Range When First Felt Anxious/Depressed',
 'MH7C': 'Have Felt Anxious/Depressed More Than Once',
 'MH8A': 'Talked to Mental Health Professional When Anxious/Depressed',
 'MH8B': 'Engaged in Religious/Spiritual Activities When Anxious/Depressed',
 'MH8C': 'Talked to Friends or Family When Anxious/Depressed',
 'MH8D': 'Took Prescribed Medication When Anxious/Depressed',
 'MH8E': 'Improved Healthy Lifestyle Behaviors When Anxious/Depressed',
 'MH8F': 'Made a Change to Work Situation When Anxious/Depressed',
 'MH8G': 'Made a Change to Personal Relationships When Anxious/Depressed',
 'MH8H': 'Spent Time in Nature/The Outdoors When Anxious/Depressed',
 'MH9A': 'How Helpful Was Talking to Mental Health Professional When Anxious/Depressed',
 'MH9B': 'How Helpful Was Engaging in Religious or Spiritual Activities When Anxious/Depressed',
 'MH9C': 'How Helpful Was Talking to Friends or Family When Anxious/Depressed',
 'MH9D': 'How Helpful Was Taking Prescribed Medication When Anxious/Depressed',
 'MH9E': 'How Helpful Was Improving Healthy Lifestyle Behaviors When Anxious/Depressed',
 'MH9F': 'How Helpful Was Making a Change to Work Situation When Anxious/Depressed',
 'MH9G': 'How Helpful Was Making a Change to Personal Relationships When Anxious/Depressed',
 'MH9H': 'How Helpful Was Spending Time in Nature/The Outdoors When Anxious/Depressed',
 'W27': 'Used Social Media in Past 30 Days',
 'W28': 'How Often Use Social Media',
 'W29': 'How Often See Information About Health on Social Media',
 'W30': 'Believe Science or Teachings of Your Religion',
 'WP21757': 'Extent Life Has Been Affected by Coronavirus Situation [Note: This is a Gallup World Poll question]',
 'WP21758': 'Temporarily Stopped Working at Job or Business as a Result of Coronavirus Situation [Note: This is a Gallup World Poll question]',
 'WP21759': 'Lost Job or Business as a Result of Coronavirus Situation [Note: This is a Gallup World Poll question]',
 'WP21760': 'Worked Less Hours at Job or Business as a Result of Coronavirus Situation [Note: This is a Gallup World Poll question]',
 'WP21761': 'Received LESS Money Than Usual From Employer or Business as a Result of Coronavirus Situation [Note: This is a Gallup World Poll question]',
 'WP21768': 'Agree to Be Vaccinated if Coronavirus Vaccine Was Available at No Cost [Note: This is a Gallup World Poll question]',
 'age_mh': 'Age first experienced anxiety/depression (combined WP21101 & WP21102 responses)',
 'Age': 'Age',
 'age_var1': 'Age cohort (3 categories)',
 'age_var2': 'Age cohort (4 categories, with older age group)',
 'age_var3': 'Age cohort (with 15-24 year old group for mental health items)',
 'Gender': 'Gender',
 'Education': 'Education Level',
 'Household_Income': 'Per Capita Income Quintiles',
 'Global11Regions': 'Global regions used in report analysis',
 'wbi': 'Country income level -- World Bank most recent definition',
 'Subjective_Income': 'Feelings About Household Income',
 'EMP_2010': 'Employment Status'}

In [40]:
#dict(data["COUNTRYNEW"].value_counts())

## Cas de la France

In [71]:
data_fr = data[data["pays"]=="France"]

In [59]:
t ={"Confiance Science":pyshs.tri_a_plat(data_fr,"confiance_science","poids"),
"Confiance Hopital":pyshs.tri_a_plat(data_fr,"confiance_hopital","poids"),
"Confiance Médecins":pyshs.tri_a_plat(data_fr,"confiance_medecins","poids"),
"Confiance Gouvernement":pyshs.tri_a_plat(data_fr,"confiance_gouvernement","poids"),
   "Confiance rebouteux":pyshs.tri_a_plat(data_fr,"confiance_rebouteux","poids")}
pd.concat(t,axis=1)

                     Confiance Science                 Confiance Hopital  \
                     Effectif redressé Pourcentage (%) Effectif redressé
1-Beaucoup                       558.9            55.9             685.1
2-Un peu                         382.2            38.2             250.2
3-Peu ou pas du tout              52.7             5.3              61.1
4-NA                               6.2             0.6               3.7
Total                           1000.0           100.0            1000.1

                                     Confiance Médecins                  \
                     Pourcentage (%)  Effectif redressé Pourcentage (%)
1-Beaucoup                      68.5              827.9            82.8
2-Un peu                        25.0              141.5            14.2
3-Peu ou pas du tout             6.1               28.2             2.8
4-NA                             0.4                2.4             0.2
Total                          100.0             1000.0           100.0

                     Confiance Gouvernement                  \
                          Effectif redressé Pourcentage (%)
1-Beaucoup                            216.7            21.7
2-Un peu                              346.6            34.7
3-Peu ou pas du tout                  429.9            43.0
4-NA                                    6.8             0.7
Total                                1000.0           100.1

                     Confiance rebouteux
                       Effectif redressé Pourcentage (%)
1-Beaucoup                         160.1            16.0
2-Un peu                           294.2            29.4
3-Peu ou pas du tout               496.2            49.6
4-NA                                49.5             5.0
Total                             1000.0           100.0

In [60]:
pyshs.tri_a_plat(data_fr,"gouvernants_valorisent_scientifiques","poids")

                      Effectif redressé  Pourcentage (%)
1-Beaucoup                        222.4             22.2
2-Un peu                          472.2             47.2
3-Peu ou pas du tout              291.3             29.1
4-NA                               14.1              1.4
Total                            1000.0             99.9

In [74]:
pyshs.tri_a_plat(data_fr,"socialmedia_month","poids")

       Effectif redressé  Pourcentage (%)
No                 308.5             30.8
Yes                691.5             69.2
Total             1000.0            100.0

In [73]:
pyshs.tri_a_plat(data_fr,"socialmedia_freq","poids")

                       Effectif redressé  Pourcentage (%)
1-Almost every hour                101.0             14.6
2-At least once a day              400.9             58.0
3-A few days a week                145.8             21.1
4-Less frequently                   39.6              5.7
5-DK/Refused                         4.2              0.6
Total                              691.5            100.0

In [72]:
pyshs.tri_a_plat(data_fr,"socialmedia_healthinfo","poids")

                                 Effectif redressé  Pourcentage (%)
1-Très souvent ou tout le temps              220.5             31.9
2-Parfois                                    334.0             48.3
3-Jamais                                     137.0             19.8
Total                                        691.5            100.0

In [75]:
pyshs.tri_a_plat(data_fr,"science_religion","poids")

                                         Effectif redressé  Pourcentage (%)
(It depends)                                          38.5              5.6
(Science and my religion dont disagree)               22.5              3.3
DK/Refused                                             9.3              1.4
Science                                              513.1             75.1
The teachings of your religion                       100.1             14.6
Total                                                683.5            100.0

In [76]:
pyshs.tri_a_plat(data_fr,"covid_impact","poids")

            Effectif redressé  Pourcentage (%)
(DK)                      0.8              0.1
A lot                   306.7             30.7
Not at all              212.1             21.2
Some                    480.4             48.0
Total                  1000.0            100.0

In [77]:
pyshs.tri_a_plat(data_fr,"vaccin","poids")

                     Effectif redressé  Pourcentage (%)
(DK)                              31.7              3.2
No, would not agree              401.4             40.1
Yes, would agree                 566.8             56.7
Total                            999.9            100.0

### Tableaux croisés

In [80]:
pyshs.tableau_croise(data_fr,"socialmedia_healthinfo","vaccin")

,(DK),"No, would not agree","Yes, would agree",Total
1-Très souvent ou tout le temps,9 (4.1%),97 (44.1%),114 (51.8%),220 (100%)
2-Parfois,10 (2.9%),144 (42.0%),189 (55.1%),343 (100%)
3-Jamais,5 (3.5%),53 (37.1%),85 (59.4%),143 (100%)
Total,24 (3.4%),294 (41.6%),388 (55.0%),706 (100%)

In [81]:
pyshs.tableau_croise(data_fr,"socialmedia_freq","vaccin")

,(DK),"No, would not agree","Yes, would agree",Total
1-Almost every hour,1.0 (1.0%),47.0 (45.6%),55.0 (53.4%),103 (100%)
2-At least once a day,19.0 (4.6%),164.0 (39.5%),232.0 (55.9%),415 (100%)
3-A few days a week,4.0 (2.8%),67.0 (46.2%),74.0 (51.0%),145 (100%)
4-Less frequently,0.0 (0.0%),14.0 (35.9%),25.0 (64.1%),39 (100%)
5-DK/Refused,0.0 (0.0%),2.0 (50.0%),2.0 (50.0%),4 (100%)
Total,24.0 (3.4%),294.0 (41.6%),388.0 (55.0%),706 (100%)

In [79]:
pyshs.tableau_croise(data_fr,"science_religion","vaccin")

,(DK),"No, would not agree","Yes, would agree",Total
(It depends),3.0 (9.4%),8.0 (25.0%),21.0 (65.6%),32 (100%)
(Science and my religion dont disagree),2.0 (9.1%),10.0 (45.5%),10.0 (45.5%),22 (100%)
DK/Refused,0.0 (0.0%),5.0 (50.0%),5.0 (50.0%),10 (100%)
Science,14.0 (2.8%),212.0 (41.8%),281.0 (55.4%),507 (100%)
The teachings of your religion,5.0 (5.2%),33.0 (34.4%),58.0 (60.4%),96 (100%)
Total,24.0 (3.6%),268.0 (40.2%),375.0 (56.2%),667 (100%)

In [82]:
pyshs.tableau_croise(data_fr,"confiance_hopital","vaccin")

,(DK),"No, would not agree","Yes, would agree",Total
1-Beaucoup,23.0 (3.4%),254.0 (37.7%),396.0 (58.8%),673 (100%)
2-Un peu,8.0 (3.1%),113.0 (44.5%),133.0 (52.4%),254 (100%)
3-Peu ou pas du tout,3.0 (4.5%),39.0 (58.2%),25.0 (37.3%),67 (100%)
4-NA,0.0 (0.0%),0.0 (0.0%),6.0 (100.0%),6 (100%)
Total,34.0 (3.4%),406.0 (40.6%),560.0 (56.0%),1000 (100%)

In [83]:
pyshs.tableau_croise(data_fr,"confiance_science","vaccin")

,(DK),"No, would not agree","Yes, would agree",Total
1-Beaucoup,20.0 (3.5%),212.0 (36.7%),345.0 (59.8%),577 (100%)
2-Un peu,13.0 (3.6%),166.0 (45.5%),186.0 (51.0%),365 (100%)
3-Peu ou pas du tout,1.0 (1.9%),26.0 (49.1%),26.0 (49.1%),53 (100%)
4-NA,0.0 (0.0%),2.0 (40.0%),3.0 (60.0%),5 (100%)
Total,34.0 (3.4%),406.0 (40.6%),560.0 (56.0%),1000 (100%)

In [86]:
pyshs.tableau_croise(data_fr,"connaissance_science","vaccin")

,(DK),"No, would not agree","Yes, would agree",Total
1-Beaucoup,4.0 (2.4%),64.0 (38.8%),97.0 (58.8%),165 (100%)
2-Un peu,28.0 (4.3%),258.0 (39.6%),365.0 (56.1%),651 (100%)
3-Peu ou pas du tout,2.0 (1.1%),83.0 (45.4%),98.0 (53.6%),183 (100%)
4-NA,0.0 (0.0%),1.0 (100.0%),0.0 (0.0%),1 (100%)
Total,34.0 (3.4%),406.0 (40.6%),560.0 (56.0%),1000 (100%)

In [87]:
pyshs.tableau_croise(data_fr,"connaissance_science","comprendre_science")

,1-Beaucoup,2-Un peu,3-Peu ou pas du tout,4-NA,Total
1-Beaucoup,107.0 (64.8%),46.0 (27.9%),12.0 (7.3%),0.0 (0.0%),165 (100%)
2-Un peu,340.0 (52.2%),251.0 (38.6%),60.0 (9.2%),0.0 (0.0%),651 (100%)
3-Peu ou pas du tout,66.0 (36.1%),71.0 (38.8%),46.0 (25.1%),0.0 (0.0%),183 (100%)
4-NA,0.0 (0.0%),0.0 (0.0%),0.0 (0.0%),1.0 (100.0%),1 (100%)
Total,513.0 (51.3%),368.0 (36.8%),118.0 (11.8%),1.0 (0.1%),1000 (100%)